vim.filetype.add({
	extension = {
		sbat = "sh",
		conf = "config",
		rasi = "css",
		tmpl = "gotmpl",
	},
	pattern = {
		["~/%.config/mutt/%a*"] = "muttrc",
		[".*/tasks/.*.yml"] = "yaml.ansible",
		[".*/main.yml"] = "yaml.ansible",
		[".*/vars/.*.yml"] = "yaml.ansible",
		[".*/playbooks/.*.yml"] = "yaml.ansible",
		[".*/docker-compose.yml"] = "yaml",
		[".*/fontconfig/%a*"] = "xml",
		[".*/templates/.*.yml.j2"] = "jinja2.yaml",
		[".*/templates/.*.yaml.j2"] = "jinja2.yaml",
		[".*/templates/.*.json.j2"] = "jinja2.json",
		[".*/templates/.*rc.j2"] = "jinja2.rc",
		[".*/templates/.*.sh.j2"] = "jinja2.sh",
		[".*/templates/.*.xml.j2"] = "jinja2.xml",
		[".*/templates/.*.toml.j2"] = "jinja2.toml",
		[".*/templates/.*.ini.j2"] = "jinja2.toml",
		[".*/templates/.*.conf.j2"] = "jinja2.conf",
		[".*/templates/.*.config.j2"] = "jinja2.javascript",
		[".*/templates/.*.css.j2"] = "jinja2.css",
		[".*/templates/conf.d/.*.conf.j2"] = "jinja2.nginx",
	},
})
