local present, symbols = pcall(require, "aerial")
if not present then
    return
end
symbols.setup({
    open_automatic = false,
    placement = "edge",
    attach_mode = "global",
    close_automatic_events = { "unfocus" },
    backends = { "lsp", "treesitter", "markdown", "man" },
    layout = { min_width = 28 },
    show_guides = true,
    lazy_load = true,
    filter_kind = false,
    icons = {
        Array = "☷",
        Boolean = "◕",
        Class = "⁐",
        Constructor = "☂",
        Constant = "π",
        Enum = "ζ",
        EnumMember = "@",
        Event = "!",
        Field = "⊟",
        File = "⊡",
        Function = "ƒ",
        Interface = "♺",
        Key = "*",
        Method = "ƒ",
        Module = "◫",
        Namespace = "ξ",
        Null = "∅",
        Number = "#",
        Object = "☁",
        Operator = "+",
        Package = "◫",
        Property = "✓",
        String = "T",
        Struct = "◧",
        TypeParameter = "⊞",
        Variable = "Ψ",
        Collapsed = "▶",
    },
    guides = {
        mid_item = "├ ",
        last_item = "└ ",
        nested_top = "│ ",
        whitespace = "  ",
    },
    keymaps = {
        ["[y"] = "actions.prev",
        ["]y"] = "actions.next",
        ["[Y"] = "actions.prev_up",
        ["]Y"] = "actions.next_up",
        ["{"] = false,
        ["}"] = false,
        ["[["] = false,
        ["]]"] = false,
    },
})
