# :vim: set ft=yaml.ansible:
---
current_user: "{{ lookup('env', 'USER') }}"
stable_release: true # use neovim stable
terminal: "/usr/bin/alacritty" # terminal executable e.g. /usr/bin/alacritty

# ~~ (0) FEATURE CONFIGURATION ~~

dap_enabled: false # enable dap core, which is nvim dap, dap ui and python dap
lsp_enabled: true # enable lsp core, which is mason, lspconfig, none-ls

# Default plugins to toggle-on/enable. Some are toggle-able (indicated as such),
# which means the setting only turns them on/off by default.

lsp_features:
  virtual_text: false # virtual text diagnostic.
  inlay_hints: false # default inlay hints (toggle-able).

ui_features:
  animate: true # non-blocking smooth scrolling (toggle-able).
  indent_lines: true # show fancy indent lines (toggle-able).
  tabline: false # display a bar at the top showing opened buffers.
  hlargs: true # enable different highlight for function args (toggle-able).

edit_features:
  completion: true # fancy text completion (toggle-able).

syntax_features:
  typst: false # enable typst syntax.
  quarto: false # enable quarto integrations.
  markdown: true # enable markdown integrations.
  org: false # enable orgmode syntax.
  tex: true # enable tex integrations.

# ~~ (1) WORKSPACES ~~

# Declare workspaces for quick access to scoped searches using a frecency algo.
frecency_workspaces:
  - conf: "$HOME/.config"
  - scripts: "$HOME/scripts"
  - dot: "$HOME/dotfiles"
  - zsh: "$HOME/.config/zsh"
  - nvim: "$HOME/.config/nvim"
  - projects: "$HOME/projects"
  - go: "$HOME/projects/go"
  - org: "$HOME/sftpgo/notes"

# ~~ (2) TREESITTER ~~

# Treesitter sources to ensure installed.
# See: (https://github.com/nvim-treesitter/nvim-treesitter?tab=readme-ov-file#supported-languages)
treesitter_sources:
  - "python"
  - "html"
  - "c"
  - "cpp"
  - "bibtex"
  - "css"
  - "json"
  - "json5"
  - "hjson"
  - "vim"
  - "java"
  - "javascript"
  - "cmake"
  - "ssh_config"
  - "latex"
  - "lua"
  - "markdown_inline"
  - "markdown"
  - "bash"
  - "diff"
  - "dockerfile"
  - "gitignore"
  - "git_config"
  - "gitcommit"
  - "git_rebase"
  - "regex"
  - "ini"
  - "muttrc"
  - "passwd"
  - "php"
  - "rasi"
  - "scss"
  - "sxhkdrc"
  - "yaml"
  - "toml"
  - "comment"
  - "org"
  - "rust"
  - "norg"
  - "xml"
  - "go"
  - "gomod"
  - "gosum"
  - "gowork"
  - "gotmpl"
  - "make"

# ~~ (3) VANITY ~~

dap_signs: # set the symbols for DAP (appear on signcolumn)
  - Breakpoint: "⚑"
  - BreakpointCondition: "⚑"
  - LogPoint: "★"
  - Stopped: "☛"
  - BreakpointRejected: "☒"

lsp_signs: # set the symbols for LSP (appear on statusline)
  - Error: "*"
  - Warn: "!"
  - Hint: "?"
  - Info: "i"

lsp_kind_icons: # set the symbols for LSP kinds (appear in various places)
  - Array: "※"
  - Boolean: "B"
  - Calendar: "C"
  - Class: "@"
  - Collapsed: "▶"
  - Color: "%"
  - Constructor: "#"
  - Constant: "π"
  - Copilot: "*"
  - Enum: "ζ"
  - EnumMember: "@"
  - Event: "!"
  - Field: "—"
  - File: "•"
  - Folder: "+"
  - Function: "f"
  - Interface: "†"
  - Key: "*"
  - Keyword: "*"
  - Method: "f"
  - Module: "M"
  - Namespace: "ξ"
  - "Null": "Ø"
  - Number: "#"
  - Object: "ß"
  - Operator: "⁑"
  - Package: "P"
  - Property: "✓"
  - Reference: "→"
  - Snippet: "*"
  - String: "T"
  - Struct: "@"
  - Table: "※"
  - Tag: "#"
  - TypeParameter: ":"
  - Variable: "Ψ"
  - Text: "T"
  - Unit: "$"
  - Value: "λ"
  - Watch: "W"

# ~~ (4) LSP SOURCES ~~

# These will be automatically installed by mason
# See: (https://github.com/mason-org/mason-registry/tree/main/packages)
# And: (https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md)
lsp_sources:
  - "ansiblels"
  - "clangd"
  - "bashls"
  - "jedi_language_server"
  - "vimls"
  - "cssls"
  - "typst_lsp"
  - "ruff"
  - "texlab"
  - "lua_ls"
  - "ltex"
  - "gopls"
  - "yamlls"
  - "markdown_oxide"
  - "dockerls"

# ~~ (5) NONE-LS SOURCES ~~

# These will be automatically installed by mason
# See: (https://github.com/mason-org/mason-registry/tree/main/packages)
# And: (https://github.com/nvimtools/none-ls.nvim/blob/main/doc/BUILTINS.md)

# !~~ (5a) FORMATTING SOURCES ~~!

null_formatting_sources:
  - "prettierd"
  - "shfmt"
  - "mdformat"
  - "stylua"
  - "cbfmt"
  - "goimports"
  - "gofumpt"

# !~~ (5b) HOVER SOURCES ~~!

null_hover_sources:
  - "dictionary" # needs curl
  - "printenv"

# !~~ (5c) HOVER SOURCES ~~!

null_diagnostics_sources:
  - "hadolint"
  - "commitlint"
  - "cppcheck"
  - "vint"
  - "ansiblelint"
  - "mypy"
  - "golangci_lint"

# !~~ (5d) CODE ACTIONS SOURCES ~~!

null_code_actions_sources:
  - "gitsigns"
  - "impl"
  - "gomodifytags"

# ~~ (6) OTHERS ~~

# Configure the dashboard ascii
# Put the ascii in single quotes, all on one line (linebreak \n)
starter_ascii: '  ／l、\n（ﾟ、｡７\n  l  ~ヽ\n  じしf,)ノ\n\n'

# Configure orgmode agenda files (can use globbing)
# Expects a list
org_agenda_files: []

# Plugins to load locally from ~/projects
dev_plugins:
  - dmg
