# :vim: set ft=yaml.ansible:
---
current_user: "{{ lookup('env', 'USER') }}"
stable_release: true # use neovim stable

# ~~ (0) FEATURE CONFIGURATION ~~

dap_enabled: true # enable dap core, which is nvim dap, dap ui and python dap
lsp_enabled: true # enable lsp core, which is mason, lspconfig, none-ls

lsp_features:
  breadcrumbs: false # show a bar at the top (winbar) with the current scope's symbols.
  usage: false # show number of usage for functions etc.
  inlay_hints: true # inlay hints for nvim < 0.10

func_features:
  tip: false # show a tip on startup (pretty annoying but useful if you're new)

ui_features:
  modes: true # highlight cursorline depending on the mode
  scope: true # only display buffers for under a given tab scope
  cursorword: true # highlight words that match current word under cursor
  indent_lines: true # show fancy indent lines
  tabline: false # display a bar at the top showing opened buffers

edit_features:
  biscuits: false # show the current scope level at the end of the scope.
  completion: true # text completion
  escape: true # use jk for escape
  move: true # extra line and char movements
  flash: true # quickly jump anywhere
  spider: true # smarter word movements
  rooter: true # project rooter

syntax_features:
  typst: false # enable typst syntax
  ansible: true # enable ansible syntax
  quarto: true # enable quarto integrations
  markdown: true # enable markdown integrations
  org: true # enable orgmode syntax
  tex: true # enable tex integrations
  rainbow: true # enable rainbow parens
  hlargs: true # enable different highlight for function args

# ~~ (1) WORKSPACES ~~

# Declare workspaces for quick access to scoped searches using a frecency algo.
frecency_workspaces:
  - conf: "$HOME/.config"
  - scripts: "$HOME/scripts"
  - dot: "$HOME/dotfiles"
  - zsh: "$HOME/.config/zsh"
  - nvim: "$HOME/.config/nvim"
  - projects: "$HOME/projects"
  - go: "$HOME/projects/go"
  - org: "$HOME/sftpgo/notes"

# ~~ (2) TREESITTER ~~

# Treesitter sources to ensure installed.
# See: (https://github.com/nvim-treesitter/nvim-treesitter?tab=readme-ov-file#supported-languages)
treesitter_sources:
  - "python"
  - "html"
  - "c"
  - "cpp"
  - "bibtex"
  - "css"
  - "json"
  - "vim"
  - "java"
  - "javascript"
  - "cmake"
  - "latex"
  - "lua"
  - "markdown_inline"
  - "markdown"
  - "bash"
  - "diff"
  - "dockerfile"
  - "gitignore"
  - "git_config"
  - "gitcommit"
  - "git_rebase"
  - "regex"
  - "ini"
  - "passwd"
  - "php"
  - "rasi"
  - "scss"
  - "sxhkdrc"
  - "yaml"
  - "toml"
  - "comment"
  - "org"
  - "rust"
  - "xml"
  - "go"

# ~~ (3) VANITY ~~

dap_signs: # set the symbols for DAP (appear on signcolumn)
  - Breakpoint: "⚑"
  - BreakpointCondition: "⚑"
  - LogPoint: "★"
  - Stopped: "☛"
  - BreakpointRejected: "☒"

lsp_signs: # set the symbols for LSP (appear on statusline)
  - Error: "*"
  - Warn: "!"
  - Hint: "?"
  - Info: "i"

lsp_kind_icons: # set the symbols for LSP kinds (appear in various places)
  - Array: "※"
  - Boolean: "B"
  - Calendar: "C"
  - Class: "@"
  - Collapsed: "▶"
  - Color: "%"
  - Constructor: "#"
  - Constant: "π"
  - Copilot: "*"
  - Enum: "ζ"
  - EnumMember: "@"
  - Event: "!"
  - Field: "—"
  - File: "•"
  - Folder: "+"
  - Function: "f"
  - Interface: "†"
  - Key: "*"
  - Keyword: "*"
  - Method: "f"
  - Module: "M"
  - Namespace: "ξ"
  - 'Null': "Ø"
  - Number: "#"
  - Object: "ß"
  - Operator: "⁑"
  - Package: "P"
  - Property: "✓"
  - Reference: "→"
  - Snippet: "*"
  - String: "T"
  - Struct: "@"
  - Table: "※"
  - Tag: "#"
  - TypeParameter: ":"
  - Variable: "Ψ"
  - Text: "T"
  - Unit: "$"
  - Value: "λ"
  - Watch: "W"

# ~~ (4) LSP SOURCES ~~

# These will be automatically installed by mason
# See: (https://github.com/mason-org/mason-registry/tree/main/packages)
lsp_sources:
  - "ansiblels"
  - "clangd"
  - "bashls"
  - "jedi_language_server"
  - "vimls"
  - "cssls"
  - "typst_lsp"
  - "marksman"
  - "ruff_lsp"
  - "texlab"
  - "lua_ls"
  - "gopls"
  - "yamlls"

# ~~ (5) NONE-LS SOURCES ~~

# These will be automatically installed by mason
# See: (https://github.com/mason-org/mason-registry/tree/main/packages)
# And: (https://github.com/nvimtools/none-ls.nvim/blob/main/doc/BUILTINS.md)

# !~~ (5a) FORMATTING SOURCES ~~!

null_formatting_sources:
  - "prettierd"
  - "black"
  - "shfmt"
  - "mdformat"
  - "stylua"
  - "cbfmt"

# !~~ (5b) HOVER SOURCES ~~!

null_hover_sources:
  - "dictionary" # needs curl
  - "printenv"

# !~~ (5c) HOVER SOURCES ~~!

null_diagnostics_sources:
  - "cppcheck"
  - "codespell"
  - "vint"
  - "ansiblelint"
  - "mypy"
  - "pylint"
  - "golangci_lint"

# !~~ (5d) CODE ACTIONS SOURCES ~~!

null_code_actions_sources:
  - "gitsigns"

# ~~ (6) OTHERS ~~

# Configure fd to allow a cleaner Telescope find_files output
fd_ignore_patterns:
  - "*.{png*,pdf,jpeg,jpg,svg,pm}"
  - "pictures"

# Configure the dashboard ascii
# Put the ascii in single quotes, all on one line (linebreak \n)
starter_ascii: '  ／l、\n（ﾟ、｡７\n  l  ~ヽ\n  じしf,)ノ\n\n'

