# :vim: set ft=yaml.ansible:
---
current_user: "{{ lookup('env', 'USER') }}"
stable_release: true # use neovim stable
terminal: "" # terminal executable e.g. /usr/bin/alacritty

# ~~ (0) FEATURE CONFIGURATION ~~

dap_enabled: false # enable dap core, which is nvim dap, dap ui and python dap
lsp_enabled: false # enable lsp core, which is mason, lspconfig, none-ls

# Default plugins to toggle-on/enable. Some are toggle-able (indicated as such),
# which means the setting only turns them on/off by default.

lsp_features:
  virtual_text: false # virtual text diagnostic (toggle-able).
  inlay_hints: false # default inlay hints (toggle-able).

ui_features:
  animate: true # non-blocking smooth scrolling (toggle-able).
  indent_lines: true # show fancy indent lines (toggle-able).
  tabline: false # display a bar at the top showing opened buffers.
  incline: false # display a small overlay bar at the corner showing opened buffers
  starter: false # display a custom start screen

edit_features:
  completion: true # fancy text completion (toggle-able).

syntax_features:
  typst: false # enable typst syntax.
  quarto: false # enable quarto integrations.
  markdown: false # enable markdown integrations.
  tex: false # enable tex integrations.

# ~~ (1) TREESITTER ~~

# Treesitter sources to ensure installed.
# See: (https://github.com/nvim-treesitter/nvim-treesitter?tab=readme-ov-file#supported-languages)
# Expects a list
treesitter_sources: []

# ~~ (2) VANITY ~~

dap_signs: # set the symbols for DAP (appear on signcolumn)
  - Breakpoint: "⚑"
  - BreakpointCondition: "⚑"
  - LogPoint: "★"
  - Stopped: "☛"
  - BreakpointRejected: "☒"

lsp_signs: # set the symbols for LSP (appear on statusline)
  - Error: "*"
  - Warn: "!"
  - Hint: "?"
  - Info: "i"

lsp_kind_icons: # set the symbols for LSP kinds (appear in various places)
  - Array: "※"
  - Boolean: "B"
  - Calendar: "C"
  - Class: "@"
  - Collapsed: "▶"
  - Color: "%"
  - Constructor: "#"
  - Constant: "π"
  - Copilot: "*"
  - Enum: "ζ"
  - EnumMember: "@"
  - Event: "!"
  - Field: "—"
  - File: "•"
  - Folder: "+"
  - Function: "f"
  - Interface: "†"
  - Key: "*"
  - Keyword: "*"
  - Method: "f"
  - Module: "M"
  - Namespace: "ξ"
  - 'Null': "Ø"
  - Number: "#"
  - Object: "ß"
  - Operator: "⁑"
  - Package: "P"
  - Property: "✓"
  - Reference: "→"
  - Snippet: "*"
  - String: "T"
  - Struct: "@"
  - Table: "※"
  - Tag: "#"
  - TypeParameter: ":"
  - Variable: "Ψ"
  - Text: "T"
  - Unit: "$"
  - Value: "λ"
  - Watch: "W"

# ~~ (3) LSP SOURCES ~~

# These will be automatically installed by mason
# See: (https://github.com/mason-org/mason-registry/tree/main/packages)
# Expects a list
lsp_sources: []

# ~~ (4) NONE-LS SOURCES ~~

# These will be automatically installed by mason
# See: (https://github.com/mason-org/mason-registry/tree/main/packages)
# And: (https://github.com/nvimtools/none-ls.nvim/blob/main/doc/BUILTINS.md)
# Each expects a list

# !~~ (4a) FORMATTING SOURCES ~~!

null_formatting_sources: []

# !~~ (4b) HOVER SOURCES ~~!

null_hover_sources: []

# !~~ (4c) HOVER SOURCES ~~!

null_diagnostics_sources: []

# !~~ (4d) CODE ACTIONS SOURCES ~~!

null_code_actions_sources: []

# ~~ (5) OTHERS ~~

# Configure the dashboard ascii
# Put the ascii in single quotes, all on one line (linebreak \n)
# Here is a cat
starter_ascii: '  ／l、\n（ﾟ、｡７\n  l  ~ヽ\n  じしf,)ノ\n\n'

# Plugins to load locally from ~/projects
dev_plugins: []

# zk wiki path for fzf-lua (https://github.com/zk-org/zk)
zk_wiki: ""
